### PR TITLE
Add list_types

### PR DESCRIPTION
**Pull request by MScottBlake**
I added list types to all except Account and AccountGroup classes.

### CODE REVIEW

**Comment by sheagcraig** [comment]
@MScottBlake Nice work overall. A couple of comments to prepare this for merging.

```JSSContainerObjects``` and it's children should have a list type, but I'm not sure that ```JSSFlatObject``` (e.g. ```ComputerCheckIn```) should. I may be wrong.

The property is there to facilitate adding one object to another. Can a policy have a computer check-in included? Obviously it's up to the user to "validate" in the sense that they don't try to do something that doesn't make sense.

I don't think there's any harm in terms of causing errors, of including them, but in terms of the code representing our documentation of what is possible with the JSS API and it's XML objects, we need to be sure that there is such a thing as a ```computer_check_in``` as an item in a list of another object.

For example, the way we know that the API object Sites can be included in other objects with an element with the tag "site" is because we can observe one in things like Policies. Can we validate that ```computer_check_in```, ```computer_command```, are actually *used* anywhere? And if so, is JAMF consistent about their naming across multiple object types.

I just discovered a ruby version of python-jss that I will need to mine for more information. It's written by people who have a lot more clue about this than I do!

**Comment by MScottBlake** [comment]
I see. I was under the impression that the property was being used to display it any time it was being displayed.

**Comment by sheagcraig** [comment]
Yeah, it's only use is when it is added to another object's XML. It's definitely a "I'm not sure what the proper OOP way to do this is, so I'll just make it work and move on."

**Comment by MScottBlake** [comment]
Addressed your concerns in #29. Closing this PR.

**Pull request closed without merging**
