### PR TITLE
Dynamic mount point

### PR DESCRIPTION
**Pull request by eahrold**

### CODE REVIEW

**Comment by eahrold** [comment]
Hey Shea,
Here are the changes, I've rebased onto master so It should be all caught up.

**Comment by sheagcraig** [comment]
It seems like (at least my) Casper Admin likes to mount duplicately-named shares with a space rather than a dash... e.g.: ```/Volumes/jamf``` and ```/Volumes/jamf 1```.

But OSX/Finder will use a dash. I'm not super inclined to support Casper Admin's method; just annoying really.

**Comment by eahrold** [comment]
And ultimately it shouldn't matter.

**Comment by eahrold** [comment]
Not sure if you're tracking my fork at all, but I rebased and put one more commit up that takes out some
variables in `is_mounted()` that are only referenced now during `_get_valid_mount_strings()`.

You may have already made theses changes, but here they are if you're interested.
https://github.com/eahrold/python-jss/commit/48b503d5e2ee8a2aab21f515b1c99c6cb9b5078b

**Pull request merged**
