### PR TITLE
Selects the highest protocol version of TLS that both the client and server support

### PR DESCRIPTION
**Pull request by hb3b**
For environments where TLSv1 is disabled.

### CODE REVIEW

**Comment by hb3b** [comment]
Any updates on this?

**Comment by sheagcraig** [comment]
Hey @hb3b 
I just wrote a new networking adapter to use Curl by default instead of requests, as the vast majority of users are using JSSImporter and don't know that there's python-jss backing that. Further, macOS doesn't ship with all of the required dependencies needed, and I can't script the getting of those for individual users, which is needed.

So, that being said, the requests networking is still there and available for developers who know what they're doing and want the better features that come with using Requests.

I'm out of the Casper game, so my ability to test this is extremely limited, can you help me understand what bumping the TLS protocol version _does_? 

FWIW, since we're now using Curl by default, there's less of a worry that people using JSSImporter won't have an updated OpenSSL + pyopenssl to be able to even _have_ a `ssl.PROTOCOL_TLSv1` available (it's not in the default macOS openssl / pyopenssl).

Thanks! I'm gearing up for a release soon, so now is a great time to get this in,

**Comment by sheagcraig** [comment]
@hb3b any thoughts on the comment above?

**Comment by hb3b** [comment]
Works for me! Thanks for your hard work on the JAMF tooling.

**Pull request closed without merging**
